controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_rating_delete:
    path: '/adminpanel/{id}'
    controller: 'App\Controller\DefaultController::deleteRating'
    methods: ['DELETE', 'POST']

app_rating_delete:
    path: '/{id}'
    controller: 'App\Controller\SeriesController::deleteRatingUser'
    methods: ['DELETE', 'POST']


admin_rating_approve:
    path: '/adminpanel/{id}/approve'
    controller: 'App\Controller\DefaultController::approveRating'
    methods: ['POST']
